name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: setup project
      run: bash install.sh
    - name: install pip dependencies
      run:  pip install -r packages/djangolic/requirements.txt
    - name: perform cypress tests
      run: npx nx run djangolic-e2e:e2e
